# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


def shared_pods
  use_frameworks!
  pod 'Alamofire'
  pod 'Kingfisher', '~> 7.6.1'
end

target 'AiOESports' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  shared_pods

  # Pods for AiOESports

  target 'AiOESportsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AiOESportsUITests' do
    # Pods for testing
  end

end


